#ifndef DATA_VEHICLE_COMMANDS_GLOBAL_H
#define DATA_VEHICLE_COMMANDS_GLOBAL_H

#ifdef _MSC_VER
#  if defined(DATA_VEHICLE_COMMANDS_LIBRARY)
#    define DATA_VEHICLE_COMMANDSSHARED_EXPORT __declspec(dllexport)
#  else
#    define DATA_VEHICLE_COMMANDSSHARED_EXPORT __declspec(dllexport)
#  endif
#else
#  define DATA_VEHICLE_COMMANDSSHARED_EXPORT
#endif

#endif // DATA_VEHICLE_SENSORS_GLOBAL_H
