#ifndef MODULE_TASK_MANAGEMENT_GLOBAL_H
#define MODULE_TASK_MANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_TASK_MANAGEMENT_LIBRARY)
#  define MODULE_TASK_MANAGEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_TASK_MANAGEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_TASK_MANAGEMENT_GLOBAL_H
