#ifndef MODULE_EXTERNAL_LINK_GENERIC_GLOBAL_H
#define MODULE_EXTERNAL_LINK_GENERIC_GLOBAL_H

#ifdef _MSC_VER
#if defined(MODULE_EXTERNAL_LINK_GENERIC_LIBRARY)
#  define MODULE_EXTERNAL_LINK_GENERICSHARED_EXPORT __declspec(dllexport)
#else
#  define MODULE_EXTERNAL_LINK_GENERICSHARED_EXPORT __declspec(dllimport)
#endif
#else
#  define MODULE_EXTERNAL_LINK_GENERICSHARED_EXPORT
#endif

#endif // MODULE_EXTERNAL_LINK_GENERIC_GLOBAL_H
