function NodeXY = loadGoxelGraph(fileName)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Usage: G = loadGoxelGraph(fileName)
%
% Inputs
%   fileName : path to the .txt file generated by Goxel
%   http://guillaumechereau.github.io/goxel/
%
% Output
%   G : cell array defining a graph node coordiantes 
%       G{i}.XY : returns the 2D coordinate corresponding to vertex i
%
% Note: computeConnectivity can be used to apply a distance criteria and
% compute edges
%
% A. Wolek, Sep 2018
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fid = fopen(fileName,'r');
skipLines = 3;
for i = 1:1:skipLines
    l = fgetl(fid);
end
i = 1;
while ~feof(fid)
    l = fgetl(fid);
    [data]=textscan(l,['%d %d %d %s \n']);
    % Goxel places nodes at integer values but our control points are at
    % [0.5, 1.5, ... ] so we add this offset here:
    NodeXY(i,:) = double([data{1} data{2}])';% + [0.5 0.5];
    i = i + 1;
end
end