#ifndef DATA_GENERIC_COMMAND_ITEM_TOPIC_GLOBAL_H
#define DATA_GENERIC_COMMAND_ITEM_TOPIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATA_GENERIC_COMMAND_ITEM_TOPIC_LIBRARY)
#  define DATA_GENERIC_COMMAND_ITEM_TOPICSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATA_GENERIC_COMMAND_ITEM_TOPICSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATA_GENERIC_COMMAND_ITEM_TOPIC_GLOBAL_H
