#ifndef TRANSMIT_STATUS_TYPES_H
#define TRANSMIT_STATUS_TYPES_H

enum class TransmitStatusTypes
{
    SUCCESS = 0x00,
    MAC_ACK_FAILURE = 0x01,
    COLLISION_AVOIDANCE_FAILURE = 0x02,
    NETWORK_ACK_FAILURE = 0x21,
    ROUTE_NOT_FOUND = 0x25,
    INTERNAL_RESOURCE_ERROR = 0x31,
    INTERNAL_ERROR = 0x32,
    PAYLOAD_TOO_LARGE = 0x74,
    INDIRECT_MESSAGE_REQUESTED = 0x75
};



#endif // TRANSMIT_STATUS_TYPES_H
