#ifndef MODULE_PATH_PLANNING_NASAPHASE2_GLOBAL_H
#define MODLUE_PATH_PLANNING_NASAPHASE2_GLOBAL_H

#ifdef _MSC_VER
#  if defined(MODULE_PATH_PLANNING_NASAPHASE2_LIBRARY)
#    define MODULE_PATH_PLANNING_NASAPHASE2SHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_PATH_PLANNING_NASAPHASE2SHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_PATH_PLANNING_NASAPHASE2SHARED_EXPORT
#endif

#endif // MODULE_PATH_PLANNING_NASAPHASE2_GLOBAL_H
