#ifndef I_MODULE_EVENTS_AI_SUPPORT_H
#define I_MODULE_EVENTS_AI_SUPPORT_H

#include "abstract_module_base.h"

#include "data_generic_item/mace/ai_test_parameterization.h"
#include "data_generic_command_item/mace/ai_items/ai_command_components.h"
#include "data_generic_command_item/do_items/action_set_surface_deflection.h"

namespace MaceCore
{

//!
//! \brief These represent events that any AI module may generate
//!
//! Events are messages generated by a module to be delivered to the core and the delegated appropriately
//!
class IModuleEvents_AISupport
{
public:
    virtual ~IModuleEvents_AISupport() = default;

public:

    virtual void EventAI_EventTag(const ModuleBase* sender, const command_item::Action_EventTag &obj) = 0;

    virtual void EventAI_ExecuteTestProcedural(const ModuleBase* sender, const command_item::Action_ProceduralCommand &obj) = 0;

    virtual void EventAI_InitializeTestConditions(const ModuleBase* sender, const command_item::Action_InitializeTestSetup &obj) = 0;

    virtual void EventAI_NewEvaluationTrial(const ModuleBase* sender, const DataGenericItem::AI_TestParameterization &obj) = 0;

    virtual void EventAI_SetSurfaceDeflection(const ModuleBase* sender, const command_item::Action_SetSurfaceDeflection &obj) = 0;

};

} //End MaceCore Namespace

#endif // I_MODULE_EVENTS_AI_SUPPORT_H
