#ifndef DATA_INTERFACE_MAVLINK_COMPONENTS_H
#define DATA_INTERFACE_MAVLINK_COMPONENTS_H

#define DATA_VEHICLE_MAVLINK_TYPES DataMAVLINK::EmptyMAVLINK

#include "empty_mavlink.h"

#endif // DATA_INTERFACE_MAVLINK_COMPONENTS_H
