# README
#####
# Build & Rebuild with the following command
# sudo docker build -t ubuntu1604:mace .
#####
###
# Now is a good time to learn how to use screen, otherwise the following commands will help you attach/detach and open new terminals
###
### Run and attach with a terminal with:
# sudo docker run -it ubuntu1604:mace
###
# To detach use: Ctrl+p + Ctrl+q
###
# To reattach: sudo docker attach [CONTAINER-ID] (you may have to press enter again to get the command line back)
###
# To start a new bash shell (so you don't interrupt something else you were running)
#     sudo docker exec -ti [CONTAINER-ID] bash
# With a new bash shell run "exit" instead of Ctrl+p + Ctrl+q
#####

## DON'T CHANGE THIS STUFF
#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update
RUN apt-get update
RUN apt-get update
## START CHANGING STUFF

# Install tools here, (recommended to use multiple lines so they don't have to all reinstall if you change one)
RUN apt-get install -y cmake
RUN apt-get install -y nano
RUN apt-get install -y tmux
RUN apt-get install -y git
RUN apt-get install -y qt5-default
RUN apt-get install -y libqt5serialport5-dev
RUN apt-get install -y build-essential
RUN apt-get install -y libboost-system-dev
RUN apt-get install -y python-pip 
RUN apt-get install -y python-dev
RUN pip install --upgrade pip
RUN pip install --upgrade virtualenv
