# README
#####
# Build & Rebuild with the following command
# sudo docker build -t ubuntu1604:mace .
#####
###
# Now is a good time to learn how to use screen, otherwise the following commands will help you attach/detach and open new terminals
###
### Run and attach with a terminal with:
# sudo docker run -it ubuntu1604:mace
###
# To detach use: Ctrl+p + Ctrl+q
###
# To reattach: sudo docker attach [CONTAINER-ID] (you may have to press enter again to get the command line back)
###
# To start a new bash shell (so you don't interrupt something else you were running)
#     sudo docker exec -ti [CONTAINER-ID] bash
# With a new bash shell run "exit" instead of Ctrl+p + Ctrl+q
#####

## DON'T CHANGE THIS STUFF
#Download base image ubuntu 16.04
FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN apt-get update
RUN apt-get update
## START CHANGING STUFF

# Install tools here, (recommended to use multiple lines so they don't have to all reinstall if you change one)
RUN apt-get install -y cmake
RUN apt-get install -y nano
RUN apt-get install -y tmux
RUN apt-get install -y git
RUN apt-get update
RUN apt-get install -y qt5-default
RUN apt-get install -y libqt5serialport5-dev
RUN apt-get install -y build-essential
RUN apt-get install -y libboost-system-dev
RUN apt-get install -y python-pip 
RUN apt-get install -y python-dev
RUN pip install --upgrade pip
RUN pip install --upgrade virtualenv
RUN apt-get update
RUN apt-get install -y pkg-config
RUN apt-get install -y liblz4-dev

# Install things in order of least likely to change
### MACE deps
RUN echo "TEST"
RUN git clone https://github.com/heronsystems/OpenMACE
WORKDIR /OpenMACE

# TESTING
RUN git checkout MACEDigiWrapper_Migration
# END TESTING

RUN git submodule init
RUN git submodule update
## FLANN
WORKDIR /OpenMACE/tools/flann
RUN mkdir build
WORKDIR /OpenMACE/tools/flann/build
RUN CXXFLAGS=-std=c++11 cmake ..
RUN make -j1
RUN make install

## Octomap
WORKDIR /OpenMACE/tools/octomap
RUN mkdir build
WORKDIR /OpenMACE/tools/octomap/build
RUN cmake ..
RUN make
RUN make install

## Libccd
WORKDIR /OpenMACE/tools/libccd
RUN mkdir build
WORKDIR /OpenMACE/tools/libccd/build
RUN cmake -G "Unix Makefiles" ..
RUN make
RUN make install

## FCL
# RUN cd ./tools/fcl && mkdir build && cd ./build && cmake .. -DEIGEN3_INCLUDE_DIR=/MACE/Eigen/include/eigen3/ && make && make install

### Actual MACE
## Env vars
ENV MACE_ROOT /OpenMACE
## LD conf
RUN echo "/OpenMACE/lib" > /etc/ld.so.conf.d/OpenMACE.conf

## Build mace
WORKDIR /OpenMACE

# TESTING
RUN git fetch
RUN git pull origin MACEDigiWrapper_Migration
# END TESTING

RUN mkdir build bin lib include
WORKDIR /OpenMACE/build

RUN qmake ../src/src.pro
RUN make
RUN make install
RUN ldconfig


## TMUX Configuration
COPY tmux/.tmux.conf /root/
COPY tmux/.tmux.conf.local /root/


WORKDIR /OpenMACE