#ifndef COMMSEXAMPLE_GLOBAL_H
#define COMMSEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMSEXAMPLE_LIBRARY)
#  define COMMSEXAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMSEXAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMSEXAMPLE_GLOBAL_H
