#ifndef MODULE_VEHICLE_ARDUPILOT_GLOBAL_H
#define MODULE_VEHICLE_ARDUPILOT_GLOBAL_H


#ifdef _MSC_VER
#  if defined(MODULE_VEHICLE_ARDUPILOT_LIBRARY)
#    define MODULE_VEHICLE_ARDUPILOTSHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_VEHICLE_ARDUPILOTSHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_VEHICLE_ARDUPILOTSHARED_EXPORT
#endif


#endif // MODULE_VEHICLE_ARDUPILOT_GLOBAL_H
