#ifndef DATA_TASKS_GLOBAL_H
#define DATA_TASKS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATA_TASKS_LIBRARY)
#  define DATA_TASKSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATA_TASKSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATA_TASKS_GLOBAL_H
