#ifndef MODULE_VEHICLE_ARDUPLANE_GLOBAL_H
#define MODULE_VEHICLE_ARDUPLANE_GLOBAL_H


#ifdef _MSC_VER
#  if defined(MODULE_VEHICLE_ARDUPLANE_LIBRARY)
#    define MODULE_VEHICLE_ARDUPLANESHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_VEHICLE_ARDUPLANESHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_VEHICLE_ARDUPLANESHARED_EXPORT
#endif


#endif // MODULE_VEHICLE_ARDUPLANE_GLOBAL_H
