#ifndef MODULE_RESOURCE_TASK_ALLOCATION_GLOBAL_H
#define MODULE_RESOURCE_TASK_ALLOCATION_GLOBAL_H

#ifdef _MSC_VER
#  if defined(MODULE_RESOURCE_TASK_ALLOCATION_LIBRARY)
#    define MODULE_RESOURCE_TASK_ALLOCATIONSHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_RESOURCE_TASK_ALLOCATIONSHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_RESOURCE_TASK_ALLOCATIONSHARED_EXPORT
#endif


#endif // MODULE_RESOURCE_TASK_ALLOCATION_GLOBAL_H
